# High Level results

*Figure 3.1* shows the results of the explanation framework disaggregated
primarily by explanation, and secondarily by cluster (E, S and G) and
primary source (WBG and all external sources).  Table X reflects the
entire universe of indicators studied (134 indicators total) while Table Y includes only those
in the current version of the WBG ESG-specific dataset (67 indicators total).

Overall, the "Methodology Lags" explanation is by far the dominant cause of gaps in ESG data,
where it is a contributing factor for 72 of 134 indicators overall, and 40 of 67 indicators in the
WBG's ESG dataset. This frequency likely reflects prevalence of traditional statistical indicators
used in ESG, many of which rely on inter-agency cooperation and other intrinsically time consuming
modalities to produce comparable data for all countries.

"Survey Dependencies" is the second most significant explanation, contributing to gaps for 32 of
134 indicators overall, and 18 of 67 indicators in the WBG's dataset. Most of these indicators
(75% and 83% respectively) fall under the "Social" pillar.

15 of 134 indicators overall have been dropped or deprecated by the World Bank and are no longer
maintained. Fortunately, the WBG's dataset does not contain any deprecated indicators. An
additional 11 indicators overall of which 4 are the WBG dataset have not been updated in
at least 5 years, suggesting that the underlying program may have been discontinued in some
fashion. Alternatively, some of these indicators may actually reflect an especially long "methodology
lags"; for instance, indicators produced on 5- or even 10-year intervals.

8 of 134 indicators overall and 6 of 67 indicators in the WBG dataset are subject to licensing
restrictions which may adversely impact the availability of recent data. Only 2 indicators are
affected by differences in the curation cycle, in which the WBG updates its data less frequently
than does the originating source.

Finally, 12 of 134 indicators overall and 6 of 67 indicators in the WBG dataset may by
definition not be relevant to high-income or very small economies. This explanation is a
somewhat exceptional case, as it may suggest special treatment at the analytical level
as opposed to strategies to improve country coverage in the data.

## Results by Source and Cluster ##

*Figures 3.2 and 3.2* show results of the explanation framework in percentage terms, disaggregated
by primary source and cluster respectively.
Overall, just over 73% of ESG indicators studied originate from sources other than the World Bank.
Figure X shows how this factor varies by explanation. Not surprisingly, all indicators restricted
by licenses come from external sources. On the other hand, the two explanations with the lowest
share of externally sourced indicators (and thus the highest share of World Bank sourced indicators)
are 'Curation Lags' (which only includes 2 indicators) and 'Survey Dependencies.' This is significant
because it may be easier for the World Bank to improve data coverage in areas where it is the primary
source for a significant portion of data.

Results vary significantly by cluster and explanation. All indicators classified as 'Deprecated' along
with all indicators subject to Licensing restraints are in the Environmental cluster, whereas both
indicators in the 'Curation Lags' explanation are in the Social cluster. 'Survey Dependencies' is also heavily
weighted with indicators in the Social cluster. The remaining explanations are distributed 
among clusters in roughly line with their respective portions of the overall sample.
