---
title: "ESG indicators"
author: "Andrei Ilas & Andres Castaneda"
date: "July 1, 2019"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_knit$set(root.dir = "D:/R working directory/")
```


```{r loadData, echo=FALSE}
esg <- read.csv("ESG.csv")
```

#Intro 

The paper aims at providing information on Wold Bank diseminated indicators that are relevant 

# Graphs 

Most of the indicators of interest to ESG work are handled by Wendy - 33, followed by Florina - 24, Hiroko 23, Haruna 17 and Bhaskar 14

```{r barplot}

counts <- table(esg$Internal.POC)
barplot(counts, main="Point of Contact")

  
counts <- table(esg$Highest.Frequency...Production)
barplot(counts, main="NAs")
  xlab="?"
  
counts <- table(esg$Topic)
barplot(counts, main="Topic")
  xlab="?"
    

counts <- table(esg$SOURCE1..NSO.IO.ITP.ET.)
barplot(counts, main="Collecting Entity")
  xlab="?"

counts <- table(esg$SOURCE2)
barplot(counts, main="Processing Entity")
  xlab="?"

counts <- table(esg$SOURCE3)
barplot(counts, main="Dissemination Entity")
  xlab="?"
  
counts <- table(esg$Highest.Frequency...Production)
barplot(counts, main="Production Frequency")
  xlab="?"
  
counts <- table(esg$Highest.Frequency...Update.frequency)
barplot(counts, main="Production Frequency")
  xlab="?"
  
counts <- table(esg$Source.Instrument)
barplot(counts, main="Source Instrument")
  xlab="?"

counts <- table(esg$Imputed.Data.)
barplot(counts, main="Imputation")
  xlab="?"

```

