# High Level results

* Indicators by source (WBG, UN, other 3rd party)
* Indicator-level heat map? (could also go in Updates section)
* Other?

Table X  and Y show the results of the explanation framework disaggregated
primarily by explanation, and secondarily by sector (E, S and G) and
primary source (WBG and all external sources).  Table X reflects the
entire universe of indicators studied (134 indicators total) while Table Y includes only those
in the current version of the WBG ESG-specific dataset (67 indicators total).

Overall, the "Methodology Lags" explanation is by far the dominant cause of gaps in ESG data,
where it is a contributing factor for 72 of 134 indicators overall, and 40 of 67 indicators in the
WBG's ESG dataset. This frequency likely reflects prevalence of traditional statistical indicators
used in ESG, many of which rely on inter-agency cooperation and other intrisically time consuming
modalities to produce comparable data for all countries.

"Survey Dependencies" is the second most significant explanation, contributing to gaps for 32 of
134 indicators overall, and 18 of 67 indicators in the WBG's dataset. Most of these indicators
(75% and 83% respectively) fall under the "Social" pillar.

15 of 134 indicators overall have been dropped or deprecated by the World Bank and are no longer
maintained. Fortunately, the WBG's dataset does not contain any deprecated indicators. An
additional 11 indicators overall of which 4 are the WBG dataset have not been updated in
at least 5 years, suggesting that the underlying program may have been discontinued in some
fashion.

8 of 134 indicators overall and 6 of 67 indicators in the WBG dataset are subject to licensing
restrictions which may adversely impact the availability of recent data. Only 2 indicators are
affected by differences in the curation cycle, in which the WBG updates its data less frequently
than does the originating source.

Finally, 12 of 134 indicators overall and 6 of 67 indicators in the WBG dataset may by
definition not be relevant to high-income or very small economies. This explanation is a
somewhat exceptional case, as it may suggest special treatment at the analytical level
as opposed to strategies to improve country coverage in the data.

**TODO:** break down this analysis by sector and source a bit more
