---
title: "An Analysis of Coverage Gaps in Sovereign ESG Data" 
author: Castaneda, Fujs, Herzog, & Maeda
date: "August 26, 2020"
knit: "bookdown::preview_chapter"
site: bookdown::bookdown_site 
bibliography: "bib/ESG coverage.bib" 
biblio-style: "apalike" 
link-citations: true
links-as-notes: true
colorlinks: yes
lot: yes
lof: yes
monofontoptions: "Scale=0.7" 
github-repo: worldbank/ESG_gaps_research
description: "ESG " 
documentclass: book
classoption: openany
github_url: "https://github.com/worldbank.org/ESG_gaps_research"
report_url: "https://worldbank.github.io/ESG_gaps_research"
imputation_tool_url: "https://datanalytics.worldbank.org/esg_imputation"
---

```{r setup1, include=FALSE}
library(tufte)
library(knitr)
library(kableExtra)
library(rmarkdown)

# invalidate cache when the tufte version changes


knitr::opts_chunk$set(
  warning     = FALSE,
  collapse    = TRUE,
  message     = FALSE,
  echo        = FALSE,
  fig.retina  = 3,
  fig.width   = 10,
  tidy        = FALSE, 
  cache.extra = packageVersion('tufte')
)

options(htmltools.dir.version = FALSE,
        tinytex.verbose = TRUE)

```

# Introduction {.unnumbered}

This document is the continuation of the paper *Options for Improving
Use of ESG data for Sovereign Bond Analysis* (World Bank 2018).
Following interaction with investors in sovereign bonds that use ESG
indicators in their country analyses and risk/return profiles of
sovereign securities, the World Bank Group (WBG) presented a set of
options for improving accessibility, quality (e.g. timeliness and
regularity of publication, geographic coverage) and transparency of
Emerging Markets data, in particular for ESG data. This paper aims to
continue the analysis, better understand underlying data production and
management issues that affect availability and provide recommendations
for improving the accessibility, quality and coverage of ESG indicators.

## Team {.unnumbered}

This document was written and developed by Tim Herzog, R.Andres
Castaneda Aguilar, and Tony Fujs. Andrei Ilas and Hiroko Maeda
contributed substantial research support.

## Replicability and license {.unnumbered}

This document is fully replicable and was produced in R using the [Bookdown][bookdown] package.
All the text files, codes, underlying
data, and dashboards can be found in its GitHub repository [worldbank/ESG_gaps_research][github].
The online version of this report with interactive charts is also [available in Github][report].

[report]: `r metadata$report_url`
[github]: `r metadata$github_url`
[bookdown]: https://bookdown.org/

